name: async_scope
description: A lightweight concurrency toolset to manage asynchronous tasks in dart.
version: 0.1.0
repository: https://github.com/skylon07/async_scope

environment:
  sdk: ^3.7.2

dependencies:
  # should NOT depend on flutter or flutter-dependent packages;
  # this package should be usable by pure dart applications
  # flutter: ...

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
